
char	*mfname[26*3] = {
		    "Allan", "Alex", "Anthony", 
		    "Barney", "Ben", "Bert", 
		    "Caspar", "Charles", "Crist", 
		    "Danny", "David", "Don", 
		    "Ed", "Eric", "Evan", 
		    "Felix", "Frank", "Fred", 
		    "George", "Glen", "Grant", 
		    "Harry", "Henry", "Howard", 
		    "Irving", "Isaac", "Israel", 
		    "Jesse", "John", "James", 
		    "Karl", "Ken", "Kit", 
		    "Lewis", "Lou", "Lucas", 
		    "Mac", "Mark", "Marty", 
	 	    "Ned", "Neil", "Noel",
		    "Orson", "Otto", "Owen", 
		    "Paul", "Pete", "Phil", 
		    "Quentin", "Quenton", "Quincy",
		    "Ralph", "Richard","Roger", 
		    "Sam", "Simon", "Steve", 
		    "Tadd", "Ted", "Terry", 
		    "Ulysses", "Upton", "Uriah", 
		    "Verna", "Victor", "Vivian",
	      	    "Walter", "Ward", "Willian", 
		    "Xavier",  "Xeron", "Xu",
		    "Yale", "Yancey", "Yankee", 
		    "Zack", "Zany", "Zelig", 
		    };

char	*ffname[26*3] = {
		    "Alice", "Anna", "April",
		    "Barbara", "Beth", "Betty",
		    "Carol", "Cathy", "Crystal",
		    "Debby", "Dina", "Doris",
	    	    "Elva", "Emily", "Eve",
	  	    "Fanny", "Frances", "Fulvia",
		    "Gail", "Gilda", "Ginny",
		    "Helene", "Hedy", "Hulda",
 		    "Ida", "Iris", "Ivy",
		    "Jane", "Joan", "Julie",
		    "Kate", "Kathy", "Kitty",
		    "Lara", "Linda", "Lisa",
		    "Mary", "Maria", "May",
		    "Nancy", "Nanny", "Nina", 
		    "Olga", "Olive", "Opal",
		    "Patty", "Penny", "Polly", 
		    "Queen", "Queenie", "Quack",
		    "Robin", "Rosa", "Ruby",
		    "Sandra", "Sandy", "Sophia",
		    "Tessie", "Theodosia","Thresa",
		    "Una", "Ursa", "Ursula",
		    "Vicky", "Victoria", "Violet",
		    "Wanda", "Wendy", "Wilma",
		    "Xenia", "Xoanon", "Xanthippe",
		    "Yolanda", "Yvette", "Yvonne",
		    "Zenia", "Zodoary", "Zoe",
		};

char	*lname[26*3] = {"Adams", "Alburn", "Allen",
		    "Beil", "Best", "Blum",
		    "Cate", "Cork", "Cox",
		    "Davis", "Doyle", "Duff",
		    "Edge", "Erickson", "Esser",
		    "Fabar", "Farley", "Fox",
		    "Gard", "Gerber", "Green",
		    "Hagemann", "Hart", "Hoffmann",
		    "Ice", "Ill", "Imm",
		    "Jacobs", "Johnson", "Judd",
		    "Kamps", "Keyes", "Kohl",
		    "Lewis", "Lincoln", "Little", 
		    "Marty", "Miller" ,"Murphy",
		    "Newell", "Newton", "Nichlos", 
		    "Obey", "Olsen", "Oscar",
		    "Packer", "Page", "Patterson",
		    "Quale", "Quam", "Quick",
		    "Ray", "Reed", "Rider",
		    "Saba", "Schmidt", "Scott",
		    "Tank", "Taylor", "Timm",
		    "Uhl", "Uhr", "Ullman",
	 	    "Van", "Vick", "Victor",
		    "Wagner", "Walker", "Wall",
		    "Xex", "Xistris", "Xu",
		    "Yank", "York", "Young",
		    "Zahn", "Zaph", "Zimmer"};
